spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo_ds_0?useServerPrepStmts=true&cachePrepStmts=true
    username: root
    password: